# Generated by Django 5.2.7 on 2026-01-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userachievement_achievement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_duration',
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
