# Generated by Django 5.2.7 on 2026-01-11 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_course_video_duration_alter_course_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='easy_correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='easy_fire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='hard_correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='hard_fire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='medium_correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='medium_fire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='quiz_fire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.course'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='current_difficulty_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.difficultylevel'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usercourseprogress',
            unique_together={('user', 'course')},
        ),
    ]
