# Generated by Django 5.2.7 on 2026-01-11 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usercourseprogress_easy_correct_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourseprogress',
            old_name='easy_correct_count',
            new_name='correct_easy_count',
        ),
        migrations.RenameField(
            model_name='usercourseprogress',
            old_name='hard_correct_count',
            new_name='correct_hard_count',
        ),
        migrations.RenameField(
            model_name='usercourseprogress',
            old_name='medium_correct_count',
            new_name='correct_medium_count',
        ),
        migrations.RenameField(
            model_name='usercourseprogress',
            old_name='easy_fire',
            new_name='flames_easy',
        ),
        migrations.RenameField(
            model_name='usercourseprogress',
            old_name='hard_fire',
            new_name='flames_hard',
        ),
        migrations.RenameField(
            model_name='usercourseprogress',
            old_name='medium_fire',
            new_name='flames_medium',
        ),
        migrations.RenameField(
            model_name='usercourseprogress',
            old_name='quiz_fire',
            new_name='flames_quiz',
        ),
        migrations.AlterUniqueTogether(
            name='usercourseprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='current_difficulty_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.difficultylevel'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='usercourseprogress',
            name='updated_at',
        ),
    ]
