# Generated by Django 5.2.7 on 2026-01-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_easy_correct_count_usercourseprogress_correct_easy_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourseprogress',
            name='correct_easy_count',
        ),
        migrations.RemoveField(
            model_name='usercourseprogress',
            name='correct_hard_count',
        ),
        migrations.RemoveField(
            model_name='usercourseprogress',
            name='correct_medium_count',
        ),
        migrations.RemoveField(
            model_name='usercourseprogress',
            name='flames_easy',
        ),
        migrations.RemoveField(
            model_name='usercourseprogress',
            name='flames_hard',
        ),
        migrations.RemoveField(
            model_name='usercourseprogress',
            name='flames_medium',
        ),
        migrations.RemoveField(
            model_name='usercourseprogress',
            name='flames_quiz',
        ),
    ]
