# Generated by Django 5.2.7 on 2026-01-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_usercourseprogress_correct_easy_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='fire_easy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='fire_hard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='fire_medium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='fire_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='fires_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='usercourseprogress',
            unique_together={('user', 'course')},
        ),
    ]
